name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Make build script executable
      run: chmod +x ./build.sh
    - name: Make packaging script executable
      run: chmod +x ./package.sh
    - name: Package project
      run: |
        ./build.sh linux-arm python 3.9
      shell: bash
    - name: Upload Release Asset tgz
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        #upload_url: ${{ github.event.release.upload_url }}
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: energyuse-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}-v${{ matrix.version }}.tgz
    - name: Upload Release Asset shasum
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        #upload_url: ${{ github.event.release.upload_url }}
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: energyuse-${{ env.RELEASE_VERSION }}-${{ matrix.platform }}-v${{ matrix.version }}.tgz.sha256sum
      
